### ISSUE TITLE
circular cubic spline

### ISSUE THREAD

**Issue by minecrawler** [emgyrz/cubic_spline#3]
For my application, I need the spline to form a closed graph. The last point should connect back to the first one and form a smooth figure. For example, let's say I define two points, then I would want to call a method so that a circle is calculated from it. More points would work, too, but then form an abstract form.

At the moment, this is not possible from what I see. There are 4 points defined, however they form a hard corner (at the top).
![image](https://user-images.githubusercontent.com/1130708/87476550-da322e00-c626-11ea-86f8-a91f5db04b06.png)
![image](https://user-images.githubusercontent.com/1130708/87476516-cedf0280-c626-11ea-9e0e-f1fdc752a93e.png)

Would this be feasible and in scope of this library? Unfortunately, my math is a bit rusty, so it would be hard for me to contribute without doing quiet a bit of research first :/

**Comment by emgyrz** [comment]
@minecrawler 
This is a very unusual use of this lib. In any case, it will be very difficult to draw an even circle. But now you can bend the ends of the chart a little. Use `hidden_point_at_start` and `hidden_point_at_end` options in `0.9.3` version.

Here's how it turned out for me
![1](https://user-images.githubusercontent.com/12197614/88468223-fff1e980-cee8-11ea-9e87-2c0878ccf761.png)

**Comment by minecrawler** [comment]
That looks pretty cool! I will give it a try later (after work). Thank you for implementing a solution so quickly.

**Comment by minecrawler** [comment]
Gave it a go and I can work with that, thank you!
