### ISSUE TITLE
cubic_spline redefines Result in the crate root.

### ISSUE THREAD

**Issue by virtualritz** [emgyrz/cubic_spline#5]
Aka, if a user imports the crate like this, for convenience:

```rust
use cubic_spline::*;
```

Their `Result` type is tainted. So if they have code that assumes `std::result::Result` that code breaks then with sth. like:
```
error[E0107]: wrong number of type arguments: expected 1, found 2
   --> src/foo.rs:42:13
    |
 42 | ) -> Result<(), Box<dyn std::error::Error>> {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ unexpected type argument
```

The reason is that it is in [`cubic_spline::Result`](https://docs.rs/cubic_spline/0.9.8/cubic_spline/type.Result.html).
A redefined `std` type It should be behind a module namespace. E.g. `cubic_spline::err::Result`.

**Comment by emgyrz** [comment]
I think it would be more correct to keep `Result` and `Error` at the top level. The same is done in standard library (e.g. `std::io::Result`, `std::fmt::Error`) or third-party packages (e.g. `serde_json`).

But I made a `cubic_spline::Result` with the second default generic parameter so that your error shouldn't be thrown. [src](https://docs.rs/cubic_spline/0.9.9/src/cubic_spline/v1/err.rs.html#20)

**Comment by virtualritz** [comment]
Fair enough. I just never saw this with any other crate I used so I reported it. Thanks for the fix!
